config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :tasks, :shifts

  namespace :admin do
    resources :tasks
  end
  

end

app/models/shift.rb
class Shift < ActiveRecord::Base
  has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :task_template
  belongs_to :task_state
  belongs_to :shift
end

app/models/task_category.rb
class TaskCategory < ActiveRecord::Base
end

app/models/task_location.rb
class TaskLocation < ActiveRecord::Base
end

app/models/task_note.rb
class TaskNote < ActiveRecord::Base
  belongs_to :task
end

app/models/task_state.rb
class TaskState < ActiveRecord::Base
end

app/models/task_template.rb
class TaskTemplate < ActiveRecord::Base
  belongs_to :task_location
  belongs_to :task_category

  has_many :tasks
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController

  def index
    @templates = TaskTemplate.all
  end

  def create
    @template = TaskTemplate.new(task_template_params)
    @task = @template.tasks.build
    @task.save!
    redirect_to action: :index
  end

  private
  def task_template_params
    params.require(:task_template).permit(:description)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController

  def show
    @shift = Shift.find(params[:id])
  end

  def create
    @shift = Shift.new(shift_params)
    @shift.save!

    completed_state = TaskState.find_by_name("complete")
    incompleted_state = TaskState.find_by_name("incomplete")

    # Instantiate all tasks into this shift
    TaskTemplate.all.each do |t|
      i = t.tasks.build(:task_state => incompleted_state, :shift => @shift)
      i.save!
    end

    redirect_to action: :show, id: @shift
  end

  private
  def shift_params
    params.permit(:start_at, :end_at)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    completed_state = TaskState.find_by_name("complete")

    @tasks = Task.where.not(:task_state => completed_state)
  end

  def update
    task = Task.find(params[:id])
    completed_state = TaskState.find_by_name("complete")

    task.task_state = completed_state
    task.save!

    redirect_to shift_url(task.shift)
  end

end

app/helpers/admin/tasks_helper.rb
module Admin::TasksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/tasks/_task_template_form.html.erb
<%= form_for :task_template do |f| %>

    <%= f.text_field :description %>
    
    <%= submit_tag "Create" %>
<% end %>

app/views/admin/tasks/index.html.erb
<div class="container">

  <div class="page-header">
    <h1>Tasks Administration</h1>
  </div>

  <div class="row">
      <div class="col-md-12">
          <%= render "task_template_form" %>


          <ul>
          <% @templates.all.each do |t| %>
              <li><%= t.description %></li>
          <% end %>
          </ul>

          Create New Additional (Non-Recurring) Task

    </div>
  </div>

</div>

app/views/home/index.html.erb
<div class="container">

  <div class="page-header">
    <h1>IDeATe Resources</h1>
  </div>

  <div class="row">
    <div class="col-md-12">

      <p>
        Hello, world.
      </p>

    </div>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IDeATe Resources</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shifts/show.html.erb
<div class="container">

  <div class="page-header">
    <h1>Shift Task List</h1>
  </div>

  <div class="row">
    <div class="col-md-12">

      <p>
        Please complete the following tasks during your shift:
      </p>

      <table>
        <% @shift.tasks.each do |task| %>
          <tr>
            <% if task.task_state == TaskState.find_by_name("incomplete") %>
              <td><%= task.task_template.description %></td>
            <% else %>
              <td><s><%= task.task_template.description %></s></td>
            <% end %>
            <td><%= button_to "Complete", task_url(task), { method: :put } %></td>
          </tr>
        <% end %>
      </table>

    </div>
  </div>

</div>

app/views/tasks/index.html.erb
<div class="container">

  <div class="page-header">
    <h1>Shift Task List</h1>
  </div>

  <div class="row">
    <div class="col-md-12">

      <p>
        <td><%= button_to "Begin New Shift", shifts_url %></td>
      </p>

    </div>
  </div>

</div>